const assert = require('assert');
const { Readable } = require('stream');
const Module = require('module');
class MemoryRedis{constructor(){this.kv=new Map;this.z=new Map}async get(k){return this.kv.get(k)??null}async set(k,v,o={}){if(o.nx&&this.kv.has(k))return null;this.kv.set(k,v);return'OK'}async del(k){this.kv.delete(k);return 1}async exists(k){return this.kv.has(k)?1:0}async incr(k){const n=Number(this.kv.get(k)||0)+1;this.kv.set(k,n);return n}async expire(){return 1}async ping(){return'PONG'}async zadd(k,...a){if(!this.z.has(k))this.z.set(k,new Map);a.forEach(x=>{if(x.member!==undefined)this.z.get(k).set(x.member,x.score)});return 1}async zrem(k,m){return this.z.get(k)?.delete(m)?1:0}async zrange(k,a,b,o={}){let x=[...(this.z.get(k)||[])].sort((p,q)=>p[1]-q[1]);if(o.rev)x.reverse();return x.slice(a,b+1).map(v=>v[0])}}
const redis=new MemoryRedis;let event;class StripeMock{constructor(){this.checkout={sessions:{create:async()=>({url:'https://checkout.test/1'})}};this.refunds={create:async()=>({id:'re_1'})};this.webhooks={constructEvent:()=>event}}}
const load=Module._load;Module._load=(r,p,m)=>r==='@upstash/redis'?{Redis:{fromEnv:()=>redis}}:r==='stripe'?StripeMock:load(r,p,m);
Object.assign(process.env,{TOKEN_HASH_SECRET:'t'.repeat(40),ADMIN_TOKEN:'a'.repeat(40),ADMIN_SESSION_SECRET:'s'.repeat(40),STRIPE_SECRET_KEY:'sk_test',STRIPE_WEBHOOK_SECRET:'whsec',LAUNCH_DATE:'2026-08-25',PAYMENTS_ENABLED:'true',PUBLIC_SUBMISSIONS_ENABLED:'true'});
function res(){return{headers:{},setHeader(k,v){this.headers[k]=v},end(x){this.body=x?JSON.parse(x):null},statusCode:0}}async function call(h,{method='GET',body={},query={},headers={}}={}){const r={method,body,query,headers,socket:{remoteAddress:'127.0.0.1'}},s=res();await h(r,s);return s}
(async()=>{const checkout=require('../api/checkout'),webhook=require('../api/webhook'),recover=require('../api/checkout-session'),admin=require('../api/admin'),listings=require('../api/listings'),vote=require('../api/vote'),report=require('../api/report'),manage=require('../api/manage'),health=require('../api/health');
const item={name:'Chris',age:31,area:'Rainham',country:'UK',gender:'m',seek:'w',pitch:'First round is on me if you can beat me at pool.',plat:'x',handle:'originle',explicitConsent:true,selfDeclaration:true};let r=await call(checkout,{method:'POST',body:{kind:'listing',amount:100,listing:item}});assert.equal(r.statusCode,200);const draftId=[...redis.kv.keys()].find(k=>k.startsWith('draft:')).slice(6);event={id:'evt_1',type:'checkout.session.completed',data:{object:{id:'cs_test_1',payment_status:'paid',payment_intent:'pi_1',metadata:{draftId}}}};const raw=Readable.from(['{}']);raw.method='POST';raw.headers={'stripe-signature':'x'};let s=res();await webhook(raw,s);assert.equal(s.statusCode,200);r=await call(recover,{query:{session_id:'cs_test_1'}});const owner=r.body;const signed=await call(admin,{method:'POST',query:{action:'login'},body:{token:process.env.ADMIN_TOKEN}});assert.ok(signed.headers['Set-Cookie']);const cookie=signed.headers['Set-Cookie'].split(';')[0];r=await call(admin,{query:{action:'pending'},headers:{cookie}});const id=r.body.listings[0].id;await call(admin,{method:'POST',query:{action:'moderate'},headers:{cookie},body:{listingId:id,action:'approve'}});r=await call(listings,{query:{sort:'paid'}});assert.equal(r.body.listings.length,1);r=await call(vote,{method:'POST',body:{listingId:id}});assert.equal(r.body.mogs,1);await call(report,{method:'POST',body:{listingId:id,reason:'The person is under 18'}});r=await call(admin,{query:{action:'reports'},headers:{cookie}});assert.equal(r.body.reports.length,1);await call(admin,{method:'POST',query:{action:'report-action'},headers:{cookie},body:{reportId:r.body.reports[0].id,action:'restore'}});r=await call(manage,{method:'DELETE',headers:{authorization:`Bearer ${owner.manageToken}`},body:{listingId:id}});assert.equal(r.statusCode,200);r=await call(health);assert.equal(r.body.redis,true);console.log('Originle backend flow tests: PASS')})().catch(e=>{console.error(e);process.exit(1)});
